todolist-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tasks, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todolist-app/app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

todolist-app/app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

todolist-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

todolist-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
end

todolist-app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

todolist-app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include TasksHelper
before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    if @task.save
      redirect_to root_path
      flash[:notice] = "Task created"
    else
      redirect_to root_path
      flash[:notice] = "Please try again"
    end
  end

  def edit
    @task = Task.find(params[:id])
    @status = status
    @categories = Category.all
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
    flash[:notice] = "Task edited"
  end

  def index
    @categories = Category.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end


  private

  def task_params
    params.permit(:title, :deadline, :description, :status)
  end

  def category_params
    params.require(:Category)
  end

end

todolist-app/app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

todolist-app/app/helpers/home_helper.rb
module HomeHelper
end

todolist-app/app/helpers/tasks_helper.rb
module TasksHelper
	def status
		return @task.status ? "Done" : "Not yet finished"
	end
end

todolist-app/app/views/home/index.html.erb
<h1 class="text-center mb-4">Welcome to my todolist app</h1>
<%= render 'tasks/task_form'  %>
<div class="container">
  <ul>
  <% @categories.each do  |category|%>
  <li class="title" style="display: inline-block; border: 1px solid #b2bec3; padding: 2px; background-color: #dfe6e9; border-color: #2d3436; border-radius: 5px 5px;"> <%= category.title  %> </li>
  <% end %>
  </ul>

  <% @categories.each do  |category|%>

  <div class="card" style="display: none; height: auto;">
    <ul>
      <% category.tasks.where(status: false).each do |task|  %>
      <li>
        <%= task.title  %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %>
        <% unless task.deadline.nil? %>
          , to read: <%= task.deadline.strftime('%D')  %>
        <% end %>
        <%= link_to "Edit this task", edit_task_path(task) %>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>
<br><br><br>
<div class="container">
  <div>
    <% @tasks.each do |task|  %>
      <div class="card col-3" style="margin: 0px auto; text-align: center;">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
    
<button id="previousButton" style="float: left;">Previous</button>
<button id="nextButton" style="float: right;">Next</button>

<br><br><br>

todolist-app/app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

todolist-app/app/views/layouts/_login_form.html.erb
<!-- Modal nouvel gossip -->
        <div class="modal" id="login">
          <div class="modal-dialog">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header" style="background-color: #17a2b8; color: #fff">
                <h1 class="modal-title">Login or <button type="button" class="signUpButton btn btn-secondary">Sign up</button></h1>
                <button type="button" class="close">&times;</button>
              </div>

              <div class="container">
              <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="field">
                  <%= f.label :email %><br />
                  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                </div>

                <div class="field">
                  <%= f.label :password %><br />
                  <%= f.password_field :password, autocomplete: "current-password" %>
                </div>

                <% if devise_mapping.rememberable? -%>
                  <div class="field">
                    <%= f.check_box :remember_me %>
                    <%= f.label :remember_me %>
                  </div>
                <% end -%>

              <!-- Modal footer -->
                <div class="modal-footer">
                  <div class="actions">
                    <%= f.submit "Log in", class: "btn btn-success" %>
                  </div>
                </div>
              <% end %>
              </div>


            </div>
          </div>
        </div>

todolist-app/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to "Sandbox App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <% unless user_signed_in? %>
      <li class="nav-item">
        <button type="button" class="loginButton btn btn-primary">Log in</button>
      </li>
      <li class="nav-item">
        <button type="button" class="signUpButton btn btn-secondary">Sign up</button>
      </li>
      <% else %>
      <li class="nav-item log-out">
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-dark" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
      
    </ul>
        <img class="rounded-circle" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
  </div>
</nav>

todolist-app/app/views/layouts/_signup_form.html.erb
<div id="signup" class="modal">

	<div class="modal-dialog">
		<div class="modal-content">
			<!-- Modal Header -->
              <div class="modal-header" style="background-color: #00b894; color: #fff">
                <h1 class="modal-title"><button type="button" class="loginButton btn btn-primary">Login</button> or Sign Up</h1>
                <button type="button" class="close">&times;</button>
              </div>
        <div class="container">
					<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
				  	<%= devise_error_messages! %>

				  <div class="field">
				    <%= f.label :email %><br />
				    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
				  </div>

				  <div class="field">
				    <%= f.label :password %>
				    <% if @minimum_password_length %>
				    <em>(<%= @minimum_password_length %> characters minimum)</em>
				    <% end %><br />
				    <%= f.password_field :password, autocomplete: "new-password" %>
				  </div>

				  <div class="field">
				    <%= f.label :password_confirmation %><br />
				    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
				  </div>

				  <!-- Modal footer -->
          <div class="modal-footer">
            <div class="actions">
              <%= f.submit "Sign Up", class: "btn btn-success" %>
            </div>
          </div>
				<% end %>
			</div>

		</div>
	</div>

</div>

todolist-app/app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form")  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>

              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

todolist-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= render 'layouts/login_form' %>
    <%= render 'layouts/signup_form' %>

    <div class="container">


        <%= yield %>


    </div>


  </body>
</html>

todolist-app/app/views/tasks/_task.html.erb
<li>
  <h4 class="tasktitle"><%= task.title %></h4>
  <% if task.deadline %>
  	
  ,"Deadline : " <%=  task.deadline.strftime("%D")  %><br>
  
  <% end %>
  
  <%= link_to "Edit this task", edit_task_path(task) %>
</li>

todolist-app/app/views/tasks/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form")  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

todolist-app/app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

todolist-app/app/views/tasks/create.js.erb
document.getElementById("task").querySelectorAll('ul')[0].insertAdjacentHTML("beforeend", "<%= j render 'task', task: @task %>");

todolist-app/app/views/tasks/edit.html.erb
<h4>Edit your task | <%= @status %> </h4>
<%= form_tag(task_path, method: "put", remote: true) do %>
  <% if @task.status == false %>
  <div class="form-group">
    	<strong>Check only if the task is finished</strong> <%= hidden_field_tag :status, @task.status, :id => "status"%>
  </div>
  <% end %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>


  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
  	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>
<%= button_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

todolist-app/app/views/tasks/index.html.erb
<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

<div class="container" style="display: block;">
	<% @categories.each do |category| %>
		<h1><%= category.title %></h1>
		<% category.tasks.where(status: false).each do |task| %>
			<% if user_signed_in? && category.tasks.length != 0 %>
					
				<%= render 'task', task: task  %>

			<% end %>

				<div class="collapse form">
				<%= form_tag(task_path(task.id), method: "put", remote: true) do %>
				  <div class="form-group">
				      <%= label_tag("Your task:") %>
				      <%= text_field_tag(:title, task.title) %>
				  </div>
				</div>

				  <div class="form-group">
				  	<strong>Check only if the task is finished</strong> <%= hidden_field_tag :status, task.status%>
				  	<%= hidden_field_tag :status, task.status, :id => "status#{task.id}", class: "checkbox", :data => { confirm: "Sure ?"} %>
				  </div>

				<div class="collapse">
				  <div class="form-group">
				    <%= label_tag("When is it due for ?") %>
				    <%= date_field_tag(:deadline, task.deadline)  %>
				  </div>
				  	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
				    <%= submit_tag("Update", class: "updateButton") %>
				<% end %>
				</div>

		<% end %>
	<% end %>
</div>

todolist-app/app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>